targets:
  - name: lessons
    sources:
      - /public/lesson/en/*.md
    file: /public/lesson/en/%language%.strings
    format: macosx
files:
  - source: /translation/lesson/en/*.md
    translation: /translation/lesson/%two_letters_code%/%original_file_name%
  - source: /translation/website/en/*.json
    translation: /translation/website/%two_letters_code%/%original_file_name%
  - source: /translation/keywords/en/*.json
    translation: /translation/keywords/%two_letters_code%/%original_file_name%
